### PR TITLE
3 Improvements: Entry points, tango new style classes, start server API

### PR DESCRIPTION
**Pull request by tiagocoutinho**
# Motivation

I wrote lima camera module in python (yes, yes I know, shame on me :-).
Instead of attaching it to the Lima project I would like to have it as part of my camera library.

## Entry points

It would be nice if in my project I could register the lima camera as an entry point in my setup.py:

```python
# setup.py
setup(
    name='democam',
    description="Python library for the great Demo camera",
    ...,
    entry_points={
        'Lima_tango_camera': [
            'DemoCam = democam.lima.tango'
        ]
    }
)
```

I propose that Lima tango server recognizes two entry points:

* `Lima_tango_camera`: allows a third-party library to register a new Lima tango camera
* `Lima_tango_plugin`: allows a third-party library to register a new Lima tango plugin

cf1a399 makes this possible.

## Tango new style classes

It would be great if we can write tango camera classes using the new style class (see [here](https://pytango.readthedocs.io/en/stable/server_api/server.html))
Example:
```python
from tango.server import Device, device_property, attribute


class DemoCam(Device):
    host = device_property(dtype=str)

    @attribute(dtype=float, unit='keV')
    def energy(self):
        return 10.23


def get_tango_specific_class_n_device():
    return DemoCam


def get_control(host):
    return ...
```

1d6afb9 makes this possible

## Start LimaCCDs programatically

It would be great if it was possible to start LimaCCDs from python like this:
```python
import Lima.Server.LimaCCDs
Lima.Server.LimaCCDs.main()
```

15aa1b4  makes this possible

### CODE REVIEW

**Comment by laurent-claustre** [comment]
Hi Tiago,
that looks nice, I would like to do some tests here and then merge on gitlab.esrf.fr for the new server release 1.9, is that ok for you?

**Comment by tiagocoutinho** [comment]
Hi @laurent-claustre,
Sure thing! Thanks for having the time to look at it. I am not in a hurry

**Comment by tiagocoutinho** [comment]
Thanks for the fix and for including this on the 1.9 release. It is much appreciated :-)

I guess we could close this PR now

**Comment by laurent-claustre** [comment]
Thanks Tiago for the green light :-)

**Pull request closed without merging**
